// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type INodeInfoResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsINodeInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *INodeInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &INodeInfoResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *INodeInfoResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *INodeInfoResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *INodeInfoResponse) CommonResponse(obj *CommonResponse) *CommonResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CommonResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *INodeInfoResponse) Size() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *INodeInfoResponse) MutateSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *INodeInfoResponse) NetBlockCap() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *INodeInfoResponse) MutateNetBlockCap(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *INodeInfoResponse) MemBlockCap() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *INodeInfoResponse) MutateMemBlockCap(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func INodeInfoResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func INodeInfoResponseAddCommonResponse(builder *flatbuffers.Builder, CommonResponse flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(CommonResponse), 0)
}
func INodeInfoResponseAddSize(builder *flatbuffers.Builder, Size int32) {
	builder.PrependInt32Slot(1, Size, 0)
}
func INodeInfoResponseAddNetBlockCap(builder *flatbuffers.Builder, NetBlockCap int32) {
	builder.PrependInt32Slot(2, NetBlockCap, 0)
}
func INodeInfoResponseAddMemBlockCap(builder *flatbuffers.Builder, MemBlockCap int32) {
	builder.PrependInt32Slot(3, MemBlockCap, 0)
}
func INodeInfoResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
