// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NetBlockPWriteBackend struct {
	_tab flatbuffers.Table
}

func GetRootAsNetBlockPWriteBackend(buf []byte, offset flatbuffers.UOffsetT) *NetBlockPWriteBackend {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NetBlockPWriteBackend{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NetBlockPWriteBackend) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NetBlockPWriteBackend) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NetBlockPWriteBackend) PeerID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NetBlockPWriteBackend) Address() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NetBlockPWriteBackendStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NetBlockPWriteBackendAddPeerID(builder *flatbuffers.Builder, PeerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(PeerID), 0)
}
func NetBlockPWriteBackendAddAddress(builder *flatbuffers.Builder, Address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Address), 0)
}
func NetBlockPWriteBackendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
