// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NetBlockBackend struct {
	_tab flatbuffers.Table
}

func GetRootAsNetBlockBackend(buf []byte, offset flatbuffers.UOffsetT) *NetBlockBackend {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NetBlockBackend{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NetBlockBackend) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NetBlockBackend) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NetBlockBackend) PeerID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NetBlockBackend) Address() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NetBlockBackendStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NetBlockBackendAddPeerID(builder *flatbuffers.Builder, PeerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(PeerID), 0)
}
func NetBlockBackendAddAddress(builder *flatbuffers.Builder, Address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Address), 0)
}
func NetBlockBackendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
