// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NetINodeCommitSizeInDBRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsNetINodeCommitSizeInDBRequest(buf []byte, offset flatbuffers.UOffsetT) *NetINodeCommitSizeInDBRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NetINodeCommitSizeInDBRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NetINodeCommitSizeInDBRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NetINodeCommitSizeInDBRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NetINodeCommitSizeInDBRequest) NetINodeID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NetINodeCommitSizeInDBRequest) Size() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NetINodeCommitSizeInDBRequest) MutateSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func NetINodeCommitSizeInDBRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NetINodeCommitSizeInDBRequestAddNetINodeID(builder *flatbuffers.Builder, NetINodeID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(NetINodeID), 0)
}
func NetINodeCommitSizeInDBRequestAddSize(builder *flatbuffers.Builder, Size uint64) {
	builder.PrependUint64Slot(1, Size, 0)
}
func NetINodeCommitSizeInDBRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
