// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NetINodeFlushRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsNetINodeFlushRequest(buf []byte, offset flatbuffers.UOffsetT) *NetINodeFlushRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NetINodeFlushRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NetINodeFlushRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NetINodeFlushRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NetINodeFlushRequest) NetINodeID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NetINodeFlushRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NetINodeFlushRequestAddNetINodeID(builder *flatbuffers.Builder, NetINodeID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(NetINodeID), 0)
}
func NetINodeFlushRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
