// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SNetPeer struct {
	_tab flatbuffers.Table
}

func GetRootAsSNetPeer(buf []byte, offset flatbuffers.UOffsetT) *SNetPeer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SNetPeer{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SNetPeer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SNetPeer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SNetPeer) PeerID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SNetPeer) Address() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SNetPeerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SNetPeerAddPeerID(builder *flatbuffers.Builder, PeerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(PeerID), 0)
}
func SNetPeerAddAddress(builder *flatbuffers.Builder, Address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Address), 0)
}
func SNetPeerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
