// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UploadJobBackend struct {
	_tab flatbuffers.Table
}

func GetRootAsUploadJobBackend(buf []byte, offset flatbuffers.UOffsetT) *UploadJobBackend {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UploadJobBackend{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *UploadJobBackend) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UploadJobBackend) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UploadJobBackend) PeerID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UploadJobBackend) Address() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UploadJobBackendStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UploadJobBackendAddPeerID(builder *flatbuffers.Builder, PeerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(PeerID), 0)
}
func UploadJobBackendAddAddress(builder *flatbuffers.Builder, Address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Address), 0)
}
func UploadJobBackendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
