// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UploadJobBackend struct {
	_tab flatbuffers.Table
}

func GetRootAsUploadJobBackend(buf []byte, offset flatbuffers.UOffsetT) *UploadJobBackend {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UploadJobBackend{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *UploadJobBackend) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UploadJobBackend) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UploadJobBackend) PeerID(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *UploadJobBackend) PeerIDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func UploadJobBackendStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UploadJobBackendAddPeerID(builder *flatbuffers.Builder, PeerID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(PeerID), 0)
}
func UploadJobBackendStartPeerIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func UploadJobBackendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
