// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package swalprotocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CommonResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsCommonResponse(buf []byte, offset flatbuffers.UOffsetT) *CommonResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommonResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CommonResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommonResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommonResponse) Code() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CommonResponse) MutateCode(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *CommonResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CommonResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CommonResponseAddCode(builder *flatbuffers.Builder, Code int32) {
	builder.PrependInt32Slot(0, Code, 0)
}
func CommonResponseAddError(builder *flatbuffers.Builder, Error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Error), 0)
}
func CommonResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
