// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package swalprotocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TopicPrepareNetBlockRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTopicPrepareNetBlockRequest(buf []byte, offset flatbuffers.UOffsetT) *TopicPrepareNetBlockRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TopicPrepareNetBlockRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TopicPrepareNetBlockRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TopicPrepareNetBlockRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TopicPrepareNetBlockRequest) TopicID() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicPrepareNetBlockRequest) MutateTopicID(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *TopicPrepareNetBlockRequest) FsINodeID() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicPrepareNetBlockRequest) MutateFsINodeID(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TopicPrepareNetBlockRequest) IndexInNetINode() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicPrepareNetBlockRequest) MutateIndexInNetINode(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func TopicPrepareNetBlockRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TopicPrepareNetBlockRequestAddTopicID(builder *flatbuffers.Builder, TopicID int64) {
	builder.PrependInt64Slot(0, TopicID, 0)
}
func TopicPrepareNetBlockRequestAddFsINodeID(builder *flatbuffers.Builder, FsINodeID uint64) {
	builder.PrependUint64Slot(1, FsINodeID, 0)
}
func TopicPrepareNetBlockRequestAddIndexInNetINode(builder *flatbuffers.Builder, IndexInNetINode int32) {
	builder.PrependInt32Slot(2, IndexInNetINode, 0)
}
func TopicPrepareNetBlockRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
