// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package swalprotocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TopicPrepareFsINodeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTopicPrepareFsINodeRequest(buf []byte, offset flatbuffers.UOffsetT) *TopicPrepareFsINodeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TopicPrepareFsINodeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TopicPrepareFsINodeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TopicPrepareFsINodeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TopicPrepareFsINodeRequest) TopicID() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicPrepareFsINodeRequest) MutateTopicID(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *TopicPrepareFsINodeRequest) FsINodeID() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicPrepareFsINodeRequest) MutateFsINodeID(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func TopicPrepareFsINodeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TopicPrepareFsINodeRequestAddTopicID(builder *flatbuffers.Builder, TopicID int64) {
	builder.PrependInt64Slot(0, TopicID, 0)
}
func TopicPrepareFsINodeRequestAddFsINodeID(builder *flatbuffers.Builder, FsINodeID uint64) {
	builder.PrependUint64Slot(1, FsINodeID, 0)
}
func TopicPrepareFsINodeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
