// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package solofsprotocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NetINodePReadRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsNetINodePReadRequest(buf []byte, offset flatbuffers.UOffsetT) *NetINodePReadRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NetINodePReadRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NetINodePReadRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NetINodePReadRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NetINodePReadRequest) NetINodeID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NetINodePReadRequest) Offset() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NetINodePReadRequest) MutateOffset(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *NetINodePReadRequest) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NetINodePReadRequest) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func NetINodePReadRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func NetINodePReadRequestAddNetINodeID(builder *flatbuffers.Builder, NetINodeID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(NetINodeID), 0)
}
func NetINodePReadRequestAddOffset(builder *flatbuffers.Builder, Offset uint64) {
	builder.PrependUint64Slot(1, Offset, 0)
}
func NetINodePReadRequestAddLength(builder *flatbuffers.Builder, Length int32) {
	builder.PrependInt32Slot(2, Length, 0)
}
func NetINodePReadRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
