// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sdfsprotocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NetINodePReadResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsNetINodePReadResponse(buf []byte, offset flatbuffers.UOffsetT) *NetINodePReadResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NetINodePReadResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NetINodePReadResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NetINodePReadResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NetINodePReadResponse) CommonResponse(obj *CommonResponse) *CommonResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CommonResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *NetINodePReadResponse) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NetINodePReadResponse) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func NetINodePReadResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NetINodePReadResponseAddCommonResponse(builder *flatbuffers.Builder, CommonResponse flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(CommonResponse), 0)
}
func NetINodePReadResponseAddLength(builder *flatbuffers.Builder, Length int32) {
	builder.PrependInt32Slot(1, Length, 0)
}
func NetINodePReadResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
